# -*- coding: utf-8 -*-
"""Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q96dXryGKOpqG91Yp_lm_ip2fprg0-p-
"""

from IPython.display import HTML, display

html = r'''
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<style>
body{
    font-family:'Poppins',sans-serif;
    background:#ffffff;
    margin:0;
    padding:0;
}

.container{
    max-width:1200px;
    margin:30px auto;
    padding:20px;
}

/* Header */
.hero{
    background:#ffffff;
    border-radius:28px;
    padding:40px 45px;
    box-shadow:0 12px 35px rgba(0,0,0,0.06);
    margin-bottom:28px;
}

.hero small{
    color:#2E7D32;
    font-weight:700;
    letter-spacing:4px;
    text-transform:uppercase;
    font-size:14px;
}

.hero h1{
    margin:18px 0 12px 0;
    font-size:52px;
    line-height:1.12;
    color:#111111;
}

.hero h1 span{
    color:#1B5E20;
}

.line{
    width:140px;
    height:6px;
    border-radius:20px;
    background:linear-gradient(90deg,#1B5E20,#43A047,#A5D6A7);
    margin:20px 0 24px 0;
}

.hero p{
    color:#2E7D32;
    font-size:20px;
    line-height:1.6;
    margin:0;
}

.hero .footer{
    color:#7a7a7a;
    font-size:14px;
    margin-top:26px;
}

/* Protocol cards */
.protocols{
    display:flex;
    gap:18px;
    margin-bottom:26px;
    flex-wrap:wrap;
}

.protocol{
    flex:1;
    min-width:220px;
    background:#ffffff;
    border-radius:24px;
    padding:22px;
    box-shadow:0 10px 28px rgba(0,0,0,0.05);
    cursor:pointer;
    transition:all .25s ease;
    border:2px solid transparent;
}

.protocol:hover{
    transform:translateY(-6px);
    box-shadow:0 16px 38px rgba(0,0,0,0.08);
}

.protocol.active{
    border-color:#2E7D32;
    background:linear-gradient(135deg,#F4FBF6,#FFFFFF);
}

.protocol .icon{
    font-size:28px;
    margin-bottom:10px;
}

.protocol .title{
    font-size:20px;
    font-weight:700;
    color:#111111;
}

.protocol .sub{
    font-size:14px;
    color:#666666;
    margin-top:4px;
}

/* Tabs */
.tabs{
    display:flex;
    gap:12px;
    flex-wrap:wrap;
    margin-bottom:24px;
}

.tab-btn{
    padding:12px 20px;
    border-radius:999px;
    border:none;
    background:#F3F5F4;
    color:#333333;
    font-weight:600;
    cursor:pointer;
    transition:all .2s ease;
}

.tab-btn.active{
    background:#1B5E20;
    color:#ffffff;
    box-shadow:0 8px 18px rgba(27,94,32,0.25);
}

/* Content */
.content{
    background:#ffffff;
    border-radius:28px;
    padding:34px;
    box-shadow:0 12px 32px rgba(0,0,0,0.05);
    min-height:280px;
}

.content h2{
    margin-top:0;
    color:#1B5E20;
    font-size:30px;
}

.content p,.content li{
    color:#333333;
    font-size:17px;
    line-height:1.8;
}

.badge{
    display:inline-block;
    margin-top:14px;
    padding:8px 14px;
    border-radius:999px;
    background:#E8F5E9;
    color:#1B5E20;
    font-weight:700;
    font-size:14px;
}
</style>
</head>
<body>

<div class="container">

    <div class="hero">
        <small>Artificial Intelligence • Deep Learning</small>
        <h1>Cannabis Classification<br>Using Auxiliary Classifier Generative Adversarial Network (<span>ACGAN</span>)</h1>
        <div class="line"></div>
        <p>Single-Subject Cannabis EEG Analysis:<br><b>Eye-Closed</b> versus <b>Flanker Task</b></p>
        <div class="footer">Google Colab Visualization Dashboard</div>
    </div>

    <div class="protocols">
        <div class="protocol active" onclick="selectProtocol(this,'Single Subject')">
            <div class="icon">👤</div>
            <div class="title">Single Subject</div>
            <div class="sub">40 EEG CSV files</div>
        </div>
        <div class="protocol" onclick="selectProtocol(this,'10 Subjects')">
            <div class="icon">👥</div>
            <div class="title">10 Subjects</div>
            <div class="sub">Multi-subject analysis</div>
        </div>
        <div class="protocol" onclick="selectProtocol(this,'30 Subjects')">
            <div class="icon">👥</div>
            <div class="title">30 Subjects</div>
            <div class="sub">Large-scale analysis</div>
        </div>
    </div>

    <div class="tabs">
        <button class="tab-btn active" onclick="openTab(event,'overview')">Overview</button>
        <button class="tab-btn" onclick="openTab(event,'dataset')">Dataset</button>
        <button class="tab-btn" onclick="openTab(event,'prep')">Preprocessing</button>
        <button class="tab-btn" onclick="openTab(event,'acgan')">ACGAN</button>
        <button class="tab-btn" onclick="openTab(event,'models')">Models</button>
        <button class="tab-btn" onclick="openTab(event,'results')">Results</button>
    </div>

    <div class="content" id="content">
        <h2>🏠 Overview</h2>
        <p>This dashboard presents an interactive workflow for cannabis EEG analysis using ACGAN. Select a protocol and navigate through the tabs to explore dataset information, preprocessing steps, model development, and experimental results.</p>
    </div>

</div>

<script>
const content = document.getElementById('content');

const pages = {
  overview: `
    <h2>🏠 Overview</h2>
    <p>Interactive research dashboard for cannabis EEG classification using ACGAN.</p>
    <ul>
      <li>EEG Dataset Management</li>
      <li>Feature Extraction Workflow</li>
      <li>ACGAN-based Data Augmentation</li>
      <li>SVM, Random Forest, and CNN 1D Evaluation</li>
    </ul>`,

  dataset: `
    <h2>📂 Dataset</h2>
    <p><b>EEG Recordings (CSV Files)</b></p>
    <ul>
      <li>BCF (Before Cannabis Oil – Eyes Closed) × 10</li>
      <li>ACF (After Cannabis Oil – Eyes Closed) × 10</li>
      <li>BF (Before Cannabis Oil – Flanker Task) × 10</li>
      <li>AF (After Cannabis Oil – Flanker Task) × 10</li>
    </ul>
    <div class="badge">Total Dataset : 40 EEG CSV Files</div>`,

  prep: `
    <h2>⚙️ Preprocessing</h2>
    <p><b>Extracted EEG Features</b></p>
    <ul>
      <li>Band Power (BP)</li>
      <li>Relative Power (RP)</li>
      <li>Entropy (EN)</li>
      <li>Hjorth Parameters (HJ)</li>
    </ul>
    <p><b>Frequency Bands</b></p>
    <ul>
      <li>Alpha</li><li>Beta</li><li>Delta</li><li>Gamma</li><li>Theta</li>
    </ul>`,

  acgan: `
    <h2>🚀 ACGAN Modeling</h2>
    <p><b>Input</b>: Feature vectors from the baseline preprocessing stage.</p>
    <p><b>Process</b>:</p>
    <ul>
      <li>Train Auxiliary Classifier GAN (ACGAN)</li>
      <li>Generate Synthetic EEG Samples</li>
    </ul>
    <p><b>Output</b>:</p>
    <ul>
      <li>Synthetic BF</li>
      <li>Synthetic AF</li>
      <li>Synthetic BCF</li>
      <li>Synthetic ACF</li>
    </ul>`,

  models: `
    <h2>🧠 Models</h2>
    <p>Baseline and final classification models used in the experiment:</p>
    <ul>
      <li>Support Vector Machine (SVM)</li>
      <li>Random Forest (RF)</li>
      <li>CNN 1D</li>
    </ul>`,

  results: `
    <h2>📊 Results</h2>
    <p>Performance evaluation will be displayed here, including:</p>
    <ul>
      <li>Accuracy</li>
      <li>Precision</li>
      <li>Recall</li>
      <li>F1 Score</li>
      <li>Confusion Matrix</li>
      <li>ROC Curve</li>
    </ul>`
};

function openTab(evt, name){
  document.querySelectorAll('.tab-btn').forEach(btn => btn.classList.remove('active'));
  evt.currentTarget.classList.add('active');
  content.innerHTML = pages[name];
}

function selectProtocol(el, name){
  document.querySelectorAll('.protocol').forEach(card => card.classList.remove('active'));
  el.classList.add('active');
  console.log('Selected protocol:', name);
}
</script>

</body>
</html>
'''

display(HTML(html))